#!/bin/bash
# Install symbolic from Octave Forge
octave --eval "pkg install -forge symbolic"
# Force automatic load in kernel
mkdir -p /home/jovyan/.octave
# Force automatic load in session
echo "pkg load symbolic;" >> ~/.octaverc

